#!/bin/bash

# File path for the generated AUTHORS file
AUTHORS_FILE="AUTHORS"

# Header for the AUTHORS file
echo "# File @generated by hack/generate-authors.sh. DO NOT EDIT." > ../$AUTHORS_FILE
echo "# This file lists all contributors to the repository." >> ../$AUTHORS_FILE
echo "# See hack/generate-authors.sh to make modifications." >> ../$AUTHORS_FILE
echo "" >> ../$AUTHORS_FILE

# Use git to get a list of unique authors from the commit history
git log --format='%aN <%aE>' | sort -u >> ../$AUTHORS_FILE

echo "AUTHORS file generated successfully!"

